heartbeat.monitors:
- type: http
  schedule: '@every 5s'
  urls:
    - http://service1:3000/healthcheck
    - http://service2:3000/healthcheck

- type: icmp
  schedule: '@every 5s'
  hosts:
    - elasticsearch
    - kibana

processors:
- add_cloud_metadata: ~

output.elasticsearch:
  hosts: '${ELASTICSEARCH_HOSTS:elasticsearch:9200}'
  username: '${ELASTICSEARCH_USERNAME:}'
  password: '${ELASTICSEARCH_PASSWORD:}'

setup.kibana:
  host: "kibana:5601"
